export const FETCH_CHARACTERS_START = 'FETCH_CHARACTERS_START';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_ERROR = 'FETCH_CHARACTERS_ERROR';
export const FETCH_CHARACTERS_SEARCH_SUCCESS = 'FETCH_CHARACTERS_SEARCH_SUCCESS';


export const FETCH_CHARACTERS_DETAILS_START = 'FETCH_CHARACTERS_DETAILS_START';
export const FETCH_CHARACTERS_DETAILS_SUCCESS = 'FETCH_CHARACTERS_DETAILS_SUCCESS';
export const FETCH_CHARACTERS_DETAILS_ERROR = 'FETCH_CHARACTERS_DETAILS_ERROR';

